package com.etallonage;

public class Main {
    public static void main(String[] args) {

        String input = "ckmb52fldxkseven3fkjgcbzmnr7\r\n" + //
                "gckhqpb6twoqnjxqplthree2fourkspnsnzxlz1\r\n" + //
                "2onetwocrgbqm7\r\n" + //
                "frkh2nineqmqxrvdsevenfive\r\n" + //
                "four9two\r\n" + //
                "six7sixqrdfive3twonehsk\r\n" + //
                "xkvsone2\r\n" + //
                "one65\r\n" + //
                "rggxsff1seven\r\n" + //
                "djbcgrrtqdshpqqzj43rgcr\r\n" + //
                "br89fivetwoqggnxjfourtl3\r\n" + //
                "zoneight47five5sixjxd74\r\n" + //
                "4five1\r\n" + //
                "5seveneighteightzzbnzsvdjnkvndsxlttfour\r\n" + //
                "htdcmsl12ninethreepkqtdlvtl\r\n" + //
                "twocghtvtdlfchfqnjhrfour19\r\n" + //
                "rptwofiveonecvlldmppxtrvj3\r\n" + //
                "6gqsvsqpzxj\r\n" + //
                "5twomgkzsvg\r\n" + //
                "4ninedflntfsn1\r\n" + //
                "4threethree\r\n" + //
                "43two6eight9\r\n" + //
                "4gqnkntjthree9one45\r\n" + //
                "9lmjgqnkxqvfrzhbcfrlltjxjlkjfrlmb3\r\n" + //
                "ninethreejkcbplfg4kseventwo\r\n" + //
                "mbkfgktwolbvsptgsixseven1oneightzvm\r\n" + //
                "m5fvqfkkk\r\n" + //
                "tptqnsxmsevencrkdmxms55zrfmpmzv7lzqlnmbkzt\r\n" + //
                "bqccqhbdgeight7\r\n" + //
                "four7nine1eight\r\n" + //
                "8fivethndnpztzninepdkfive8\r\n" + //
                "1sixxvqdfourlnpdrfbnnx41vhqgth\r\n" + //
                "sgpkgdb9\r\n" + //
                "fivetwoq7cdprnjdjhs3three9\r\n" + //
                "1mfvptbhqshblvvvdl\r\n" + //
                "ztftqgbzld8jkcmsrdfzonemzdmbzxpfour\r\n" + //
                "dfkctqcjbmfourhszmlvtkeightthree2\r\n" + //
                "4onersrfjcskckcxcj4sevenzzzpsixeight\r\n" + //
                "1fourr5gxpone\r\n" + //
                "seven74ninersgvvmtgsix\r\n" + //
                "jvtwonefivetwosbpglbx2two\r\n" + //
                "fourfivecxgssssixtwofour4\r\n" + //
                "3zcgcjdcpbgqdfnhxtneight\r\n" + //
                "fourfour29cpbccthree44\r\n" + //
                "6six9foureight5xmfdf\r\n" + //
                "four77\r\n" + //
                "tqtnjshdmtwo3four8one27\r\n" + //
                "one52\r\n" + //
                "nine32five3six\r\n" + //
                "qcjbjrpqdtpvveightpmzs17fourjvghvl\r\n" + //
                "5293gmtdttfpmrlhvlt9\r\n" + //
                "2zonenfglkskxhn3gxbrtxtcpfive\r\n" + //
                "three5cfourfvmqlnhp4two\r\n" + //
                "three4knrdzxpr\r\n" + //
                "fmpvqkxgeightthreebdrng9tdcffvsfctwo\r\n" + //
                "jpktgx8fivegqeight5three\r\n" + //
                "7sevennine\r\n" + //
                "3two3\r\n" + //
                "nfthhzcq2\r\n" + //
                "plmbtrzbnbmt1nine\r\n" + //
                "149hvjbktkmbj8mtnrblcvfive7seven\r\n" + //
                "bfthree1\r\n" + //
                "six6kqprz86two6\r\n" + //
                "jthree6\r\n" + //
                "nine2hzrlcqrt7eight\r\n" + //
                "nnzhkhpdb8rbnqmxrfive\r\n" + //
                "rkszqnp1\r\n" + //
                "t1\r\n" + //
                "5sixlmxkgmxrgveight3\r\n" + //
                "sevenlptpdhtjpgxconedvtrrnngn8\r\n" + //
                "nlpvxbscttbbpgndnc7jvrtcjxbsxnqvfcxdcfrgtrdkjflzlrqcnmfourkznnmrv\r\n" + //
                "7kllgxpb6\r\n" + //
                "two4eightfgrsix1five7six\r\n" + //
                "one2three6hmktjgmbxhbjl\r\n" + //
                "bqjtxhntjreightsevendgcfpmkld14four\r\n" + //
                "22pgcslxtdhkhz8ninethreethreejcklznxq\r\n" + //
                "146gqthree85twoseven\r\n" + //
                "vlvxlmkfpcxsstsevencdbbdsix6\r\n" + //
                "5sixseven48\r\n" + //
                "llljbtxtrrpssrfthree9dpvrndphhn\r\n" + //
                "qkhvq5\r\n" + //
                "svrfthree8bdhjshcftdnine4\r\n" + //
                "nfqnfkpchl5pcstz\r\n" + //
                "pbx5mfkfour8\r\n" + //
                "cptwonethreeptwo9gzmlkv9\r\n" + //
                "gdpkprlzr6466fxlvfour\r\n" + //
                "dlnpklqtfivesixfptrdh9four\r\n" + //
                "onedpfskdd38qfvbjdnpglone\r\n" + //
                "4sevenseven5qf\r\n" + //
                "onepgmmhlgmtvone3c\r\n" + //
                "247tsnmkd\r\n" + //
                "threeznnnbtfive5tmdfxtwothree3ndjcszrb\r\n" + //
                "oneeight6rhfiveone\r\n" + //
                "threethreethreestvgljm4seven\r\n" + //
                "bfbrk3vqsmone39hzzxdgp6eight\r\n" + //
                "98rndphxhcbl\r\n" + //
                "57fourlntgdngzpdsjkbbxnv7\r\n" + //
                "twons4\r\n" + //
                "three4threesixtwo2hf\r\n" + //
                "lgqtcllzsevenhrrhqsmsnncmlz7\r\n" + //
                "8fnngjrxtljncbvlt7ninehfzrthree\r\n" + //
                "12mltqtqqrvjmjsbthnzpdjtwo1\r\n" + //
                "lf1onevdmn2\r\n" + //
                "3twozlqnddmrsixslphpvb\r\n" + //
                "five4nrtcjmvj\r\n" + //
                "cksgmkszrbsrgfkq7tqjxsshxxh7vngsnjt\r\n" + //
                "mfiveone7\r\n" + //
                "kkvtwone5sevenfcfnngpmjktrpxk7djgzmdthreehpp\r\n" + //
                "fxbgtcjp4pxpjv5rbfllhfcpfive8\r\n" + //
                "2gxrkjdtvxmnvs76\r\n" + //
                "npvvleightlpd354vrfh1\r\n" + //
                "zbnzdlzpqzsixnine4sevenqtddzzm6\r\n" + //
                "6cxrhdvzbmthree98\r\n" + //
                "77eightnine32four\r\n" + //
                "56tshj77one\r\n" + //
                "161xk26mspxkchfourfive\r\n" + //
                "onenineljnsmvmfb7\r\n" + //
                "6hxvmqtwo\r\n" + //
                "khzninetwo3pbtsqxlqj3\r\n" + //
                "1nine3\r\n" + //
                "6xrzjskblfq\r\n" + //
                "kbtsbckkonethreetwofour7lgcbxmjkjpnine\r\n" + //
                "fivethreecrjznine7\r\n" + //
                "8qxjdsspgn\r\n" + //
                "vdoneightsix7h9\r\n" + //
                "5bsjl\r\n" + //
                "gfllsrrrmzbfqdrlnvtdzr3\r\n" + //
                "7hs2\r\n" + //
                "1onelseventwo\r\n" + //
                "fivetwo3\r\n" + //
                "2gnxv9sevenseven\r\n" + //
                "gmmhshzvsixzssixseven6fivehbdvsjdz\r\n" + //
                "75onegckzsnpnine1xfslhfour6\r\n" + //
                "sixgjhnfvsjnrsixeightnine49\r\n" + //
                "nineseven929rlsdkcpbjrjdlptjbzp2\r\n" + //
                "9hbpplffngltfourpgk\r\n" + //
                "twoldknnqxkkvvdjldqthree373\r\n" + //
                "cceight9two\r\n" + //
                "zmeightwohkgs6\r\n" + //
                "6sevenfdmqkss4fivethreesevenfourqfnsvvsj\r\n" + //
                "4two9njeightnine\r\n" + //
                "two3gzseveneightfour88eight\r\n" + //
                "2clqj\r\n" + //
                "1ndvbhbtql\r\n" + //
                "five4sixseven5ghlgbmdgfnqpfdm\r\n" + //
                "34dt\r\n" + //
                "9sevenrl5\r\n" + //
                "dpbpqppsixngvmkflllcrtn8\r\n" + //
                "sixgvsctkrp53sbsx\r\n" + //
                "nine9qdrqfourjc\r\n" + //
                "zvppfjpqch24\r\n" + //
                "sg4txzzfoursevenninethreesqcdznksix\r\n" + //
                "one3six2\r\n" + //
                "5bgdjzxbrlsl3sixlbxtjdpgfkjmq2\r\n" + //
                "drsldhgjtrvmmz3jgrp6\r\n" + //
                "qkeightwosix95nine445cfnine\r\n" + //
                "fivetwo82scjct7onegblrqrggv9\r\n" + //
                "threepfgljkghzc9\r\n" + //
                "8qvzljppstpnpeight9\r\n" + //
                "8nine98tkxcfqtg\r\n" + //
                "sevensix4two\r\n" + //
                "2eightthree\r\n" + //
                "cvhhmcgknj6threefive87\r\n" + //
                "seveneight7dsvqnjsjsqlkeightwovzt\r\n" + //
                "71oneseven9fiveeightnh\r\n" + //
                "pdjtzxbgjxb3vzfdnjbthree\r\n" + //
                "xqpfourmpddnfcc4one5\r\n" + //
                "jnrms1fkssgpvvlrmf\r\n" + //
                "jbnkeightone6zldns85sixnine\r\n" + //
                "1fourbqfgxscdxmkvdpsrm\r\n" + //
                "eightsixone8mjbrqkplkqntjdlfourpjdcs\r\n" + //
                "lxdsp6prmfglvdfz9eight7sevensixone\r\n" + //
                "qdksixvmsevent7xlvmtzdkhb\r\n" + //
                "8spqjvhplpzldpthree2\r\n" + //
                "zqfvpq7pz22\r\n" + //
                "nnfbpfour1\r\n" + //
                "one9ninetwovrclctwo\r\n" + //
                "344six98seven\r\n" + //
                "kqkj9qqvfxn\r\n" + //
                "seven1fivethree\r\n" + //
                "shlnhgq2c3oneseveneightwodv\r\n" + //
                "eightthreepkcxlk7threeonethreetwo\r\n" + //
                "pgmbhrzzqmvkjl57fourqk8gxjmbfqcjs9\r\n" + //
                "eight5oneights\r\n" + //
                "ninenineeightvkrsrkgh8\r\n" + //
                "svnfdxxftkgzpjqxzkmbbcfourvfsg3two6twonezqn\r\n" + //
                "mnvqcmkqvjlqvtltgdpktr3dkgkbt\r\n" + //
                "sixmg29pplfzrsqhlvfeight\r\n" + //
                "glzsbmzqjj43\r\n" + //
                "1zqrnpqrcbzdsnfour67zpsxpkbbkmfgrzm\r\n" + //
                "kxbbcjjksix7sixeightnine\r\n" + //
                "zbnhsdxgt5sixsixeightlsdqrgseven\r\n" + //
                "ninezxrllznbcvmldxfbvjx5fivedtpdhsjgk8\r\n" + //
                "reightwo7\r\n" + //
                "fiveninenftgfourjbdkxtxcb38two\r\n" + //
                "sixlpck4sixzcppvhzkchmnpvqjjgffourj\r\n" + //
                "34pmfdthreetwo\r\n" + //
                "7zbnnkqone5three\r\n" + //
                "qxkmhcllcqkk5qrqseven47\r\n" + //
                "one62brghc8s\r\n" + //
                "twotwo1xvgcxbthree\r\n" + //
                "three83dfqgjlc8eight\r\n" + //
                "twofive8l1twocqmcccgdm\r\n" + //
                "two6cnine\r\n" + //
                "h2sfnczjmslpmlvdlzrs\r\n" + //
                "9nbblsvxbhdxqfour8\r\n" + //
                "kfzcsg6sixonevrbchsjtfivenbz\r\n" + //
                "mgtlqcdtwo7qxmszcqpjdplccxzccsixone5nine\r\n" + //
                "mtfpphckdn1eightpdtkssqlxdhtlmcjxb\r\n" + //
                "jbphmjjjrg2159eight\r\n" + //
                "zqskrzb1pgfouronevxscgtlccl\r\n" + //
                "lxvpgrck8fxhxm\r\n" + //
                "fournrnlfive1xt\r\n" + //
                "3nsjnb\r\n" + //
                "eight1three513nine\r\n" + //
                "39eightsevenfourbgd1mbljzone\r\n" + //
                "6two88five2pjpp\r\n" + //
                "fourjlftf7six1xsktfhcdff\r\n" + //
                "3kcntzlmnnhhmtmlftggqljkrvninetwo\r\n" + //
                "threesixonexlvxrblq24\r\n" + //
                "xpgzzrcckdlnrczxndplbpcb452\r\n" + //
                "ninembdnhhnhhzmvmtdjtkzmb9ncq9one\r\n" + //
                "4fivebrqrxftwo\r\n" + //
                "84tqzbcvgdrgpzpxjrone83zgzpsix\r\n" + //
                "99five\r\n" + //
                "mgsevenqgkckfhbfnine3\r\n" + //
                "2seventhree\r\n" + //
                "8fivethreefive2fivethreefive\r\n" + //
                "scrtqsevenjmxlvjrrbdtqgrdghfivethree7seven\r\n" + //
                "sevensix946onesevenfour\r\n" + //
                "dzn14\r\n" + //
                "nineqbxvponekvfffs96zjfhpthree\r\n" + //
                "53twoqknxnxqbcone\r\n" + //
                "fhonerone7fourpmxskkmmx7\r\n" + //
                "eightlq4fourfourdbsdrvhhs17\r\n" + //
                "nnpgtgcbvrggctbtkzht5xmkhtnnn7brpxjcxdrone\r\n" + //
                "threecxnqkmrrpmzdljstdbfmk5seven\r\n" + //
                "sdptbzqhn7sixnine8\r\n" + //
                "five7jdzdzfqfivesevengtznjmqrblkkzkgvt\r\n" + //
                "fclvllfthx47sixbhq16\r\n" + //
                "9mbmsxbn\r\n" + //
                "three82fiveseven4\r\n" + //
                "p1kzmzpbhmcthree\r\n" + //
                "eightj3681nmgt8\r\n" + //
                "2two7\r\n" + //
                "jdbjlvxhhzzsnmcqldrldeight6nine4\r\n" + //
                "2threefive\r\n" + //
                "foursevenrmfhjvzdv8bpbrvblll1onetwofive\r\n" + //
                "65cfgkcrhbjk\r\n" + //
                "6onecjxzxb72gmrblthx\r\n" + //
                "4jlrvckc9\r\n" + //
                "doneightghmjzzrfourfdzxflm51nineseven7xkxt\r\n" + //
                "r5eightone\r\n" + //
                "nkgknm1\r\n" + //
                "rxbsnnzbrs4two4\r\n" + //
                "1pqvmfh\r\n" + //
                "r2vpdpkzqcs85\r\n" + //
                "gtfzjnnhsknvjnmnine98\r\n" + //
                "zrdgv4hnbpb\r\n" + //
                "7one165vddbrzpmfhskvzxdh3\r\n" + //
                "44szfpgjmvgt4eight\r\n" + //
                "dbgttrbj6five85nsqmzscksvdxks\r\n" + //
                "ffkrhbvq2\r\n" + //
                "6fourbpjrdvlk\r\n" + //
                "38eightsix\r\n" + //
                "two4fivedzpgfbtm\r\n" + //
                "3jbk46\r\n" + //
                "slpkmrstrrvthreepl9bhctdfnfzc\r\n" + //
                "nine4two5kkfmcjgxbqkttg\r\n" + //
                "1zppnmcr5sjfsbbxh48one\r\n" + //
                "8one8fourseven5\r\n" + //
                "6three7nineeight6\r\n" + //
                "96three\r\n" + //
                "91twonelt\r\n" + //
                "5sevenone2sixthreeknhzm\r\n" + //
                "2fvhgcbvg7sevenzqdtftct7tvvtkpxbrq8\r\n" + //
                "9nvr\r\n" + //
                "eightfivetwodjg9\r\n" + //
                "7four2six\r\n" + //
                "5fkzgffzpgp3\r\n" + //
                "75sevenfive\r\n" + //
                "mxtwonexsdrpkqzgm1threejqftvl\r\n" + //
                "onekxffhsqb4dkb9fivefvtcjsd\r\n" + //
                "eightone1eighteight4\r\n" + //
                "glfeight7eight4\r\n" + //
                "eightcdfjjfiveeight4fivetwo\r\n" + //
                "npxnp32kfsfjpggdtpkm5\r\n" + //
                "seven7threevcb\r\n" + //
                "xtcvsmdx2four2twonefl\r\n" + //
                "mzkgnzstwo844dcseight\r\n" + //
                "zgoneight65z1seven3\r\n" + //
                "1two5lc\r\n" + //
                "threevsrg5vdmfvpss27qzrmvmbz\r\n" + //
                "7qbcnjg1nine1seven3seven\r\n" + //
                "5fourxdxrhmxsj\r\n" + //
                "v78\r\n" + //
                "41nine\r\n" + //
                "56fmktkxvltp4bztxkqfrdthreefive4\r\n" + //
                "fourdnq1\r\n" + //
                "ctlk31srscmmdn66sevendmjjqvgj\r\n" + //
                "b7nine8ninejqqhhdnnpx5\r\n" + //
                "ninedlxdshrzfmrnnq17\r\n" + //
                "jbneightwofiversjctwogvvtprslpgfour9xcone\r\n" + //
                "dpt5hbgbnmdlthree5sixvsvqtnmndpvv\r\n" + //
                "sevenrztpgr8nine2\r\n" + //
                "four9three1keightbmljrjgxkrbjdhbckbst\r\n" + //
                "sfmztfjh49one\r\n" + //
                "seven3three7eightwovs\r\n" + //
                "48onetwosix4four4ntvrzvdztr\r\n" + //
                "mphtwone5sevenfour7\r\n" + //
                "4lgqnbdlone\r\n" + //
                "hpnmtjbcdhfhsnxqhjhhfgteighteight8one5\r\n" + //
                "cgtdtt22\r\n" + //
                "plnbntcb8seven1gkgzngxq\r\n" + //
                "7bonethreefour\r\n" + //
                "ffoureight88\r\n" + //
                "z2four3dfggfntxjbjhdr9three\r\n" + //
                "5sixgpcm9two\r\n" + //
                "sixpnlcgbcpdsixtwofour4foursix3\r\n" + //
                "dstgjlh812\r\n" + //
                "3xfhdfrgqjfourkfjone7four8\r\n" + //
                "nine4three6sevenfourthreeeight\r\n" + //
                "njvdqthkv5seven6fourtbklhrqqsixeight6\r\n" + //
                "58rcfcjdkxcj3eightlndf\r\n" + //
                "jhnt7zblnkdvhslrhpbkzdh\r\n" + //
                "7threetrlkmmlzsmtwo4dmjf94nine\r\n" + //
                "pssrhmtcv7twotwodjxvlbmnfive58\r\n" + //
                "eightseven271onefxxrfglh\r\n" + //
                "9bmtwo\r\n" + //
                "three522\r\n" + //
                "eightseventworckvnine2\r\n" + //
                "6fourtzmlrkrztvtxfcdf5\r\n" + //
                "3six4rdchffcg7\r\n" + //
                "6threedqssixnine\r\n" + //
                "fivetwo6\r\n" + //
                "sixnpkr5xbxmjcxjznpnrf8brxtmgl\r\n" + //
                "gtvg3zzbeightkphjs69pjprvhlgl\r\n" + //
                "7kclrcjbtkcr63two5\r\n" + //
                "threehpn38fivedcmfkgqqeightwovg\r\n" + //
                "hbjcsfshsjqqfive9sevenfourthree3fzjpfjzd\r\n" + //
                "five7qzhnthree1\r\n" + //
                "nxhg17j8ninejnqlnine\r\n" + //
                "ddlnxmcg2\r\n" + //
                "rxeightwopqtpqncvd481154fiveb\r\n" + //
                "sevenvbkzgzmnine4qhpptngvhh\r\n" + //
                "bkmz6nineeight69\r\n" + //
                "tqvzkqfourrj4one\r\n" + //
                "sh15nzxzhqdxd96dqht\r\n" + //
                "6rhztqrfninefsqszx\r\n" + //
                "38cngonefourrhlljvpgz5vzhmbdjj5\r\n" + //
                "8fiveddchtllpt\r\n" + //
                "13rgzljhsdjfive2six\r\n" + //
                "sevenbdnbheightfive7qbzjvlsr3\r\n" + //
                "fivejmfvtnhz1eightkcdpjsghgtwonine9\r\n" + //
                "five3bllpvnqgtzdhvprgb\r\n" + //
                "t1vcttwo\r\n" + //
                "9953three92\r\n" + //
                "9hrgxdpf\r\n" + //
                "sevennine579seven\r\n" + //
                "threekp1onefrfjbrmmpmsdsvfour\r\n" + //
                "4threefive61rrhrtdjs5\r\n" + //
                "xbmvcfqp4onesevenmkgvsnprtl65\r\n" + //
                "379\r\n" + //
                "4966dlprfxmhmqdfour6\r\n" + //
                "9lllhz8nmqxkzsevenxmbqvgqnj8\r\n" + //
                "btkxnzonesevenjmkdcc1ff32eight\r\n" + //
                "7three65one745\r\n" + //
                "seven66ninelkbmvndm3\r\n" + //
                "4three3sixeight3\r\n" + //
                "177dcxqqbqpkxgctwo\r\n" + //
                "48cjpd47sevenzgtkrdlfq\r\n" + //
                "5ppzvklbtnine212qlmt\r\n" + //
                "89tpmnr\r\n" + //
                "dh1gfgb6threeqcm3\r\n" + //
                "five83\r\n" + //
                "fzlkpx6seven2twotjlqpgldlfour49\r\n" + //
                "fiveninefivenxpzkrslxm44\r\n" + //
                "pxxbnsfoursixeight5mjkeight\r\n" + //
                "ninefivesevenz6\r\n" + //
                "djddxtdeight2vqsvdgttxonefourfhdfxszvfd8pjcvzbgp\r\n" + //
                "253seven71nine\r\n" + //
                "eight6cb71\r\n" + //
                "gfzptdj1nine5twosvtmpphj9mkhd\r\n" + //
                "hfjcpvzeight7ggqrmkmzrhbthreeeight\r\n" + //
                "chjonetwo2lqxfrbvq\r\n" + //
                "fkfmntldvleight4threethreeeightfour\r\n" + //
                "6j81threeseventwo3seven\r\n" + //
                "seightwosvsnp4\r\n" + //
                "8bqjk75254\r\n" + //
                "6seventsmnfjtn4rthrp\r\n" + //
                "9kksdvfzzpsszffouronenrqrcnine\r\n" + //
                "5dkpp8fournine4one\r\n" + //
                "4mpbzrfvj8two9sevenonenine\r\n" + //
                "jzkdrrjsnpxzxbjhb5\r\n" + //
                "three87oneonexppvhz3seven\r\n" + //
                "two39kvrmz\r\n" + //
                "vdfive8dntsz\r\n" + //
                "mthreehzdghb3eightsevenfttmjtx\r\n" + //
                "2dlnjsxlg\r\n" + //
                "7threecrrdqksqsevensixnine\r\n" + //
                "mdxhrrrfiveone6\r\n" + //
                "8nine52\r\n" + //
                "725two\r\n" + //
                "jzpxt2vcninenjgfzddk\r\n" + //
                "three29\r\n" + //
                "zjrffvdgnpeight1sevenglpfkdb\r\n" + //
                "two3qnhqvxeight\r\n" + //
                "slqdvfmeightmlhjdcvbrmsjvrk6\r\n" + //
                "two13kfxd28rzqhcdkjtbbstnhbfive\r\n" + //
                "qhdqqnjbdk8eighttwoqpthree\r\n" + //
                "one1brxnptch263eight18\r\n" + //
                "threexntmdtwokdmhf3pdkgpthree\r\n" + //
                "2three9jrcrmjvbrm\r\n" + //
                "1mmlsfsdkzkvjtwo3b\r\n" + //
                "sfkkkncf3three4seventwoqzhmcdfbhxfl\r\n" + //
                "vfnqlnrzcrzm8fourvpzxqdqsfb\r\n" + //
                "rjkhxqdmkrfive1\r\n" + //
                "2four2nine9znp6seven\r\n" + //
                "7doneone\r\n" + //
                "9threetworqlk\r\n" + //
                "eighttpclmtv4twofour5mtxxnpthreeoneightfp\r\n" + //
                "onecfjgrbsjncmpqhqvhxtfpc21nineppone\r\n" + //
                "eightlvjxmxhfive9fb\r\n" + //
                "ninenrjlmcthree3four\r\n" + //
                "eightlxrnvljrhksxzfxzbrt644\r\n" + //
                "blmjnfgsrcms31\r\n" + //
                "zsix16xtjvrtn\r\n" + //
                "lkjfpxjh1sg57xbxlsxcrsix1\r\n" + //
                "mkmdcsbgvd19ninecsevenone9\r\n" + //
                "three1p\r\n" + //
                "4prbjfour1ninesix\r\n" + //
                "pkf7sixsb\r\n" + //
                "fiveclczl8sltncdxsix\r\n" + //
                "4ninefourseven5three\r\n" + //
                "3lpchjfgbhzjbqggsfoursixseven\r\n" + //
                "twonmcfztwoqp1one5\r\n" + //
                "87sevendbqdsevenrlzkrhoneeightone\r\n" + //
                "4three4\r\n" + //
                "2tthbbcpcr36tqvfjkfs\r\n" + //
                "rtzqgsixnine4bzqhjrq8five\r\n" + //
                "eight3fivel4kd\r\n" + //
                "1fourfourdpvvghvlzxtwothree\r\n" + //
                "2gzgzmrpbztm1cgzvvrtqt\r\n" + //
                "qdrfrkncnt1eight\r\n" + //
                "smpz4mjrbthree1ninefour\r\n" + //
                "6seventhree7\r\n" + //
                "5278nlnfjrqlone8\r\n" + //
                "nine6eight\r\n" + //
                "twoqrtdsreight2dxhknhpdzz2pdbsnlpljlxkv9eightwop\r\n" + //
                "vl6eight9eightsix1lmth\r\n" + //
                "qxsevenkckxvmjkb1\r\n" + //
                "hvhlm2twotwoone\r\n" + //
                "grtlftfthtthree331dzzzoneseven\r\n" + //
                "ftpkgvrsc85cplddgnn\r\n" + //
                "lhcbzhgfjlgmcsn66\r\n" + //
                "twofourqjrltlvcmmzv8nine3ps\r\n" + //
                "knvz5four\r\n" + //
                "threefivefoureight7four\r\n" + //
                "one9fournine5\r\n" + //
                "cr8twofive7two4tlbpgbngsp\r\n" + //
                "seven6gzn8trjmzrvjthtpzld5dcqnjmtl4\r\n" + //
                "1five1fourfour8hqjzshnszhzgcchs2\r\n" + //
                "tld78blgffjksevenninekmjnrzlvxr\r\n" + //
                "15six\r\n" + //
                "fqlmqhjslgnllgs6three\r\n" + //
                "jvhmkfjzd5\r\n" + //
                "kfkxjmbrgjzmjtwo2qnh45pxrkrcpmjd\r\n" + //
                "dh119mvxlfdft6sevenqdxb\r\n" + //
                "five5jl\r\n" + //
                "jhqp2qzkfvjdfts\r\n" + //
                "teightwo6\r\n" + //
                "kscczzhftqxmbrjtm46five5hncmntrgqz\r\n" + //
                "65341\r\n" + //
                "cxjpgfourfour98spklghbv73\r\n" + //
                "5sevengnxldmlvnrzsthree\r\n" + //
                "bsn6three\r\n" + //
                "fivesixz36\r\n" + //
                "snpmdmx65five4\r\n" + //
                "vrjbjsixfour37onesscclpgxr\r\n" + //
                "four58\r\n" + //
                "nlrflkxjzbpckmprkp435\r\n" + //
                "pp78\r\n" + //
                "rhz3dblsmbl8mvmthree3svhbzb\r\n" + //
                "qtztdn4\r\n" + //
                "rqrdr5ninefivexj\r\n" + //
                "fiveone4ninesplghqrbcnmmzll4mvklfmxv\r\n" + //
                "tj3ninekvczg3cczmhkdf\r\n" + //
                "fivelnrjmn3jvlmhplj4fourkvdceight\r\n" + //
                "five6jrbkxrvmtqfvbq7pmjmdkmkv\r\n" + //
                "6gcllrgktc\r\n" + //
                "21zffhnksmjj1rcdpkcrznine\r\n" + //
                "threegpnpftrstmfive4ninefive\r\n" + //
                "1cnsixpnvrxq\r\n" + //
                "33qghllh\r\n" + //
                "gfour1rmznkmplqfsevennksglsfdqtwotwonet\r\n" + //
                "kjqcslq3nineoneightkq\r\n" + //
                "three8oneninepjpqnzccthree\r\n" + //
                "3jpfhtrfrffournmrxrpdjm\r\n" + //
                "2svsmkptdcmpkhbpmnineczjsjvlfpkckxscfour\r\n" + //
                "dqxpjsnineonenvhptwocprtsbvcl6\r\n" + //
                "ninethreesixninesixxjjjkvtbgd5hrstthree\r\n" + //
                "fivefznprpxccnk8four3twobllsjnfjnx\r\n" + //
                "ghh2skv6\r\n" + //
                "eightninethree4jbcgrqeightfive\r\n" + //
                "4ltjfxjbthreesixbrtzlbfdx7eight\r\n" + //
                "one9mvbrcc\r\n" + //
                "three5khjdjlpl4hrzqblshkxdgseven8\r\n" + //
                "czvxncr2\r\n" + //
                "eightthreedhkkpr9hqqdtwo1\r\n" + //
                "fouronetnhxgzstdx31six\r\n" + //
                "fzcnineghrfbcbhhv263\r\n" + //
                "eightfive525onexgrzfive\r\n" + //
                "zclvsg9three6eightkeighttwo\r\n" + //
                "two35bhmnlt\r\n" + //
                "9s\r\n" + //
                "xbshssrspj643four4vrjdnlf\r\n" + //
                "nineseven4ztnchhpx92\r\n" + //
                "gpfive25dvx\r\n" + //
                "1five5\r\n" + //
                "jtcstj1kqrsbhsdsk8\r\n" + //
                "eight1sixsixbnsfouronecsv\r\n" + //
                "tgplkg2hgeight\r\n" + //
                "seveneightxsgcsfxd9dpkvltrsnlkccrskrbppmkxmpt\r\n" + //
                "pddbvnrqzznqmmonesixjgpgm9rmlxvqqmdbcqhng\r\n" + //
                "xqdbsktwothxzfsmqptrjbthreesixhqgrffqcnine2\r\n" + //
                "vxvtfjsevenfivethreethreensflthreenine6\r\n" + //
                "8one9sxrczdfg2\r\n" + //
                "mdtdgjthreethreefjzqs16\r\n" + //
                "dnvpjteight6tcn\r\n" + //
                "eightnine3cdzk\r\n" + //
                "three6tzmqbzgmdeight9fiveztwo2\r\n" + //
                "1pg6three6sevenmghhdx3\r\n" + //
                "41threenine1\r\n" + //
                "ncbrrm7six2nine\r\n" + //
                "eightxrxdsnsvzddhrqvkfmseven3ntpqhsbttqmlp\r\n" + //
                "one3fourmmrhpjmnjnqxkf4ftkxsvsix\r\n" + //
                "54zdqrrmzd\r\n" + //
                "rftdstx6hdrhmqjs9b35\r\n" + //
                "fiveseven8five5\r\n" + //
                "gzfkkqznk4\r\n" + //
                "six32ckkbh\r\n" + //
                "jpk171fivesevenhbjlddveightvcqh\r\n" + //
                "71foursix7\r\n" + //
                "2nine4onelkvplzhj7onen\r\n" + //
                "4nrvsh3twoprvpgltsix1pzbdhvfour\r\n" + //
                "skvnpjfmkhmf7547tszjzmq\r\n" + //
                "two3ctthreesix3sjflprlrcg8bnhxs\r\n" + //
                "six41nmgpztwo\r\n" + //
                "dkkhmgmjtwo4seven\r\n" + //
                "8jqcmhrbmcninehbpxdjpvbk882ktjxp\r\n" + //
                "hlbhcfivetwo77three\r\n" + //
                "19ccmrmh1lgmngl8\r\n" + //
                "5eightnhfsjzjseventhreefiveeighteight\r\n" + //
                "3dkvxfive\r\n" + //
                "39zn\r\n" + //
                "cqsklnrdhtwoeight814rdncfthrjbc7\r\n" + //
                "13pfspbxkfrr\r\n" + //
                "five7sevenfourfour42tppvrfqrvz\r\n" + //
                "nboneightfour9eight7threefournmvcrgmkx7hs\r\n" + //
                "sixoneppbone5ctdhjzzrnine\r\n" + //
                "5one1nineeight1two99\r\n" + //
                "7rjvqdvgxxmb\r\n" + //
                "sixbkdpftd6\r\n" + //
                "699\r\n" + //
                "rflvscthxb9one9jtfqd\r\n" + //
                "sixtwo2hsclsg\r\n" + //
                "8nzgpt7eightfour6zhjxqjmrq53\r\n" + //
                "pddnfour1one749five\r\n" + //
                "gbbprvrq23seven77zssgktwo\r\n" + //
                "ppc2flmdjrp7twoonerjhtlv\r\n" + //
                "vlltgb8seveneight5clqsthree6\r\n" + //
                "onetwobtgdkkxv1five6lcfvkhm9three\r\n" + //
                "two8threesixsix\r\n" + //
                "5threeeight\r\n" + //
                "onespeight9twonexpr\r\n" + //
                "pzfourseven8five9five\r\n" + //
                "9mbdbphhrfeight\r\n" + //
                "fournt14\r\n" + //
                "jlcb2\r\n" + //
                "three3eightnfj2\r\n" + //
                "6four2fgsndlslkr\r\n" + //
                "8sevensxcjl6fivefivesssevenqghn\r\n" + //
                "3xgzj66svlvqgcvzzlb5vvjvmvb\r\n" + //
                "hfhmngkv64\r\n" + //
                "263six\r\n" + //
                "oneone15qtgtksjdgz27hjl9\r\n" + //
                "1six8mrrkx6\r\n" + //
                "vdhslzfgsevenfivemseven4fourq\r\n" + //
                "vdjlnrvqjb5thsevenfiveonexskqrfourhtcl\r\n" + //
                "1ninefoursix6seven\r\n" + //
                "twobvpnjmspxmgxkv4twotjjkbxfgs4\r\n" + //
                "fivefour8kfjrpdddhr\r\n" + //
                "dvbljqpznfjjp6sevengvbdxm1bnzhqmcdgpzrd1\r\n" + //
                "34cmclpfrgrjpxpjpdv\r\n" + //
                "9xcdkhtsdmtvlrtlcbsixtrjqxg\r\n" + //
                "rdhqfcseventhree9tqggvslm\r\n" + //
                "gddfoursevenrqvqdkqbr6ninecfd\r\n" + //
                "19cjpltfxspkpxkctdhjkncnbtwoone\r\n" + //
                "mseven7six4five19hjd\r\n" + //
                "jcqlxpmmj7rsrrngnq2seven\r\n" + //
                "fssvonepgqmrgbv1\r\n" + //
                "fourfivefoursixthreegjgxhbzrgx1\r\n" + //
                "fzdfbxsths5szkgkgzdmnvtnine9nqb\r\n" + //
                "rszfmx6eightnine6eightj\r\n" + //
                "three199twol7six3\r\n" + //
                "threedmxbsevenjmdvrzlfive26\r\n" + //
                "ninehkbdkc594one\r\n" + //
                "6fsix\r\n" + //
                "fiveseven51fjlx6\r\n" + //
                "bj3fivesix1\r\n" + //
                "9vxcstvpf\r\n" + //
                "threeseven6\r\n" + //
                "ninefive4twoonetwo\r\n" + //
                "8seven6\r\n" + //
                "twopxsts95\r\n" + //
                "pzhxsxnnkthree6\r\n" + //
                "6ninem591\r\n" + //
                "7drfqdsjsnfdbqp\r\n" + //
                "p2plgbninethreesixthree\r\n" + //
                "5seventnhvjfrlkggfjbmlzxhnnnsh\r\n" + //
                "seven691rjmnfzddfive\r\n" + //
                "466mmgnh\r\n" + //
                "dsctthree7\r\n" + //
                "eightqlfourzndmzltp34xjbdmpjs1\r\n" + //
                "stmprbctwo1ninesxbzqkkdqgdqhone\r\n" + //
                "sevensixeight91sixjscqxlzj4\r\n" + //
                "vrctfpbp2bdknhtwothree68ckzlgkghponeightg\r\n" + //
                "one82lzh1m9\r\n" + //
                "5dgkljnlvnthbdfeight7x9kloneightrp\r\n" + //
                "9pdsgfourzcfour51one\r\n" + //
                "3twonltnmdqttqmj6fivefivesix\r\n" + //
                "1four8szcp\r\n" + //
                "dqbrkz8xp\r\n" + //
                "3twoftqxxgdg\r\n" + //
                "sflsixzjq1\r\n" + //
                "6nine4plhvcthree\r\n" + //
                "znzdrj4526fjtszspfour9pk\r\n" + //
                "785bttrfnrtzvninehqzthfr\r\n" + //
                "6slx7six8qhppjmbcrj\r\n" + //
                "dc1fdzzsvnb\r\n" + //
                "1xfourtwo\r\n" + //
                "1mvt283\r\n" + //
                "fivecflqkthreek2\r\n" + //
                "7gtdlvbcxvrxvx1264eight\r\n" + //
                "b1pbpcsix\r\n" + //
                "fivefourzqrmbpgnqzgpzhfour9\r\n" + //
                "seventhree5cnvjmthree\r\n" + //
                "ksblnqbkgnfone8\r\n" + //
                "8fourvkhkhlsjq\r\n" + //
                "twoqjvb9zjvpfz2onesixk\r\n" + //
                "tdjmrcvsevensix1seveneight\r\n" + //
                "5mqxkkcttfivezdbcdmlfivebchqlcktpseven\r\n" + //
                "7bzsnljccxqbtq3dsfsbrlpgqjzxeight\r\n" + //
                "one4mjgfhzsjdc3crgthhjrznd\r\n" + //
                "sixthreektx8xjbdjlq\r\n" + //
                "bgvldztfivetwo3tldvpzkmonepdvppd8\r\n" + //
                "xhzm91\r\n" + //
                "oneskfoureight23\r\n" + //
                "ppsj64\r\n" + //
                "fgrf45four5\r\n" + //
                "four2two\r\n" + //
                "798jcgzf\r\n" + //
                "93mxc\r\n" + //
                "hn5q9rm2vtksix9\r\n" + //
                "cvdldzschflc9eight\r\n" + //
                "mqdtndzvv9eightkzxlgvcggrkltzlphcfq\r\n" + //
                "beightwoone6rqjcqq7sixfourrkghseven\r\n" + //
                "two9nine9foursevenfourone\r\n" + //
                "793sixzngtcbrbtjmbjbqxzpqjkn\r\n" + //
                "1five4\r\n" + //
                "x4\r\n" + //
                "qmlvsptmqhfvbfiveonemnmzshczjgsvgsgpps2seven\r\n" + //
                "28eightmt9\r\n" + //
                "1four8hbpnktmn\r\n" + //
                "6nine5threeplcsdrn96four3\r\n" + //
                "two3vdvh6\r\n" + //
                "three7fiverkjmllclbprmqgb4\r\n" + //
                "strvnllfmqm2threesixbbrjxbjvvxvjhr91\r\n" + //
                "4dbqqbdcddldhgxjrnfivehz9\r\n" + //
                "v81nnvzv\r\n" + //
                "3ssptnqhmrzbseveneightwoxdx\r\n" + //
                "ninetthree72\r\n" + //
                "556five2three\r\n" + //
                "99175onepzqpj\r\n" + //
                "8tmbfpbsninenineglvbh7gnrd\r\n" + //
                "three8zmtvxqmksfpvkfourp9twooneightzgs\r\n" + //
                "khmcnch1tb2\r\n" + //
                "5jtcggvdfzmsppshsqlhz\r\n" + //
                "249sixtwofoureight\r\n" + //
                "6sixfourxpnt\r\n" + //
                "6threen\r\n" + //
                "16qmgfjjmqnktnxgz\r\n" + //
                "kjvbk1zzqhdkgxxghxsix77\r\n" + //
                "sndnsm1741gtszjkmvxsevennine\r\n" + //
                "kzlrrrjbtrrgf5jsbgxn\r\n" + //
                "4bnfdfbgthc\r\n" + //
                "ztghxzrdprvlfx4\r\n" + //
                "54tzqlfjfnthree7twonine\r\n" + //
                "knqkbts5ffqhdsfpmdeightnfhpjcmfmrl\r\n" + //
                "jzphxleightjhxvhdrseven5mktwo\r\n" + //
                "1fivegxdknn\r\n" + //
                "3onetpqdddbhb2seven2\r\n" + //
                "7seventhreebzcqpkdck5dc\r\n" + //
                "seven71\r\n" + //
                "eighttwo1\r\n" + //
                "dfflcrcqfiveone2seven6\r\n" + //
                "qpf8\r\n" + //
                "1seven1bjsmxzr54four5\r\n" + //
                "mmztpseven836four\r\n" + //
                "three8htqhzkrxhrfourthreebdrmjsvpfb1\r\n" + //
                "zjhljpmmdms998ffjqgxgbkdbvxxppdltbrpzcbf\r\n" + //
                "rj76\r\n" + //
                "vlxnnqxr4eight\r\n" + //
                "2twoonefourtwosevenpdpfkgdhhzlbfq\r\n" + //
                "cn5five4\r\n" + //
                "hhqzsxlm45twonine\r\n" + //
                "ncszsls1z2\r\n" + //
                "ktxkkbhcxcbnffzbsix8bf4r\r\n" + //
                "xrk1bvvrxvkreighttwoeight\r\n" + //
                "4eightqbmtpsl2six\r\n" + //
                "13jzchfndpjpone\r\n" + //
                "fivefvm1sevenhjxrnkg2bfmdnbj8\r\n" + //
                "9gcfmkhqrczseven7jkshrh\r\n" + //
                "twornrbjlvsdr1threem\r\n" + //
                "njzxgftwo4two\r\n" + //
                "threertvjcmtlr7nxhghbnvkq\r\n" + //
                "6seven8drfivecvv3cr\r\n" + //
                "fivefiveddnhmz25nine7\r\n" + //
                "2eight4nine47\r\n" + //
                "nthreetwotwo67\r\n" + //
                "4mbsqbpvf7threedp4fourvvdgkvzfkz\r\n" + //
                "sixthree1twozxldcqnvdcksfiveseven\r\n" + //
                "nh2\r\n" + //
                "4rczvpnvsptwo\r\n" + //
                "foursevenone4\r\n" + //
                "5sixkvsjjqzs32kbghctffhssmg98\r\n" + //
                "zbclnpj3ncgjrpz6tcgdvjpdmkk1\r\n" + //
                "4mmsbtfivetwodgvbhrzrlh\r\n" + //
                "sfour2fivefour\r\n" + //
                "jx9\r\n" + //
                "xltwone6\r\n" + //
                "1szbglvbcblqtdqrbdqqhbfzrrq4sixfivezfb\r\n" + //
                "two8klhvgbm97eightfour6\r\n" + //
                "szslrmeightsz61eighthnhxv1\r\n" + //
                "seven42sznlgdsdgfj\r\n" + //
                "three2eight26nine\r\n" + //
                "4sevenfmxrhgkll3fivefjsxninefour\r\n" + //
                "onenlzksgpz2ggnvsmlxxsvqsix6twodbdzvkbhhl\r\n" + //
                "mxs62zfsmkgmxzl6nbsix\r\n" + //
                "9sevenlbbt9twonet\r\n" + //
                "32tworbbmnbgqjd\r\n" + //
                "jrx7mpbcvqfhfr7sixsixkqmcj\r\n" + //
                "vcdcthreefour5bbqbhxqjkqqzkdk\r\n" + //
                "onesevenfourhxfvfoursrq4n1\r\n" + //
                "six1hglqzjxfxxd4\r\n" + //
                "4lkjljr2\r\n" + //
                "3brlmgbpdnpslgcsevenxrrftvzlxc5nine\r\n" + //
                "czhmhhnrxrbzgtmvn1mbjpnrlsevenbfbztqfp\r\n" + //
                "xnctftbbm3seveneight9kpkfour\r\n" + //
                "xsixsixh5three\r\n" + //
                "2lzslqtllcpfdq3\r\n" + //
                "six2xstqpjctsxgtwo941\r\n" + //
                "sixthree6\r\n" + //
                "636bmxvvfztzvbrxbfh1four\r\n" + //
                "h4pcllfnine\r\n" + //
                "pknldv4jzlkngvqslchstsnfj7sixsevensevenb\r\n" + //
                "78threegfclmstbxt\r\n" + //
                "9three9mnkhrrlbgonethreef1six\r\n" + //
                "2bzslfdpvoneeightthreeone3jpqjk2\r\n" + //
                "1nfjttgvlsn6eight2hznlx\r\n" + //
                "7three7sevenbdngj6threeseven\r\n" + //
                "one8qdldvhjhrfsixgscfnpvbm2\r\n" + //
                "mqlhrjksdtbrvrgvpc884ngrddthzjgtjxnjq\r\n" + //
                "kpndxtponenine97\r\n" + //
                "vcpsjrxlpfqprxz7threeeight2\r\n" + //
                "ztgckbfr5twodpznplgl32rfqjhrvhgmkd\r\n" + //
                "threehfvxnkfhdgmtwo16\r\n" + //
                "6seven36qrndxhxljgkskgtjdtscczz1\r\n" + //
                "ndcqhqnvtppkfbgljkrd3xfdvqhxkx94\r\n" + //
                "sixgonebbblkbbqvccnvm2jxpvlnrbmjnsrnqgbb\r\n" + //
                "sevenmeight2rlvbkxmxfour3nine8\r\n" + //
                "72bcdrcbzffkc3oneightnc\r\n" + //
                "onesevenfour57\r\n" + //
                "sixnmplqnfx1eightfour\r\n" + //
                "nine5bh4eightseven\r\n" + //
                "7gcqthhztknjslxfbcj19\r\n" + //
                "five2fivethreedbrkgchn8\r\n" + //
                "221565\r\n" + //
                "26three83vmtlj\r\n" + //
                "nine5threeninezgjcpssevenone\r\n" + //
                "xshxdblgf8threehxkntrdn6lghpzt9\r\n" + //
                "fdfqxmn3eight6zssbgnddcv\r\n" + //
                "eight1hrrqmzjjq\r\n" + //
                "ckhpqtwodqz9r\r\n" + //
                "zbtjjffourninesix7bqz\r\n" + //
                "jeightvfdqttxmsix3pnh5lgf\r\n" + //
                "6onerqbdslg\r\n" + //
                "fivep26two\r\n" + //
                "onetwogscnvv1\r\n" + //
                "eight1487\r\n" + //
                "threekksixnine6\r\n" + //
                "69sixoneqhhrqsg\r\n" + //
                "8sevenmtcm\r\n" + //
                "three1jlbfpfdxpqpzspgcllfv\r\n" + //
                "27one\r\n" + //
                "mlmfourseven3\r\n" + //
                "sixninercgrkdpd9\r\n" + //
                "three7kmvsztmxjsixthree3bvhmhthreesdrbq\r\n" + //
                "mk7\r\n" + //
                "jstwone8fourkrlmtfk7qjvrghcbfive5\r\n" + //
                "eightchvxseven9nine252\r\n" + //
                "five68qoneeight\r\n" + //
                "seveneightfive2threetckdpkqrnqpthreevlqlq\r\n" + //
                "jlcpvfxpq867xfcjcddvjkjdfnqtnjp1\r\n" + //
                "prxzmdmbxbfljckhd7pbc5three\r\n" + //
                "92fninenhnxjlzninenqmhmmlsfqf\r\n" + //
                "ftmljhqxjdhddkbtxlbz9five\r\n" + //
                "oneone4cfsnxltqfbnzzljseven\r\n" + //
                "gbktqjbrtgsevenninexf6seventwonine\r\n" + //
                "nine3fournine\r\n" + //
                "1fourtwo17seven\r\n" + //
                "twosixmpnpdzmjxlmjsjdnkmnhmdtdg7xrbknkplsix6\r\n" + //
                "fqzqxzkgzrlkmqfour53seven2\r\n" + //
                "8three27eight4onekgrlc\r\n" + //
                "nzrlgrvfive3vdtqcqrm6\r\n" + //
                "4qfgvppninetwoone4\r\n" + //
                "threelpmgkfxoneseven8threebmjtdl4\r\n" + //
                "slkrnqlpfxcrgxmnd9one7\r\n" + //
                "fouronekbfmdrjxvn8kz1twosevenrth\r\n" + //
                "8xbvkfqmzjg\r\n" + //
                "six4xcx97lzninefivenine\r\n" + //
                "threesixhfvnjrvpf1sixseveneightfive\r\n" + //
                "8ninethreethreepdlddhdfp\r\n" + //
                "two47threefour\r\n" + //
                "61czbc4cvklssbpt\r\n" + //
                "8712st2\r\n" + //
                "lgflr1three\r\n" + //
                "ninenine9\r\n" + //
                "ptx86five\r\n" + //
                "291\r\n" + //
                "seven82three9\r\n" + //
                "mxfhmtcjpxqqsl68hpcfvjj\r\n" + //
                "1qmvjl6four\r\n" + //
                "3six84\r\n" + //
                "fivefivefourfiveeight7eightwods\r\n" + //
                "2seven5five2d\r\n" + //
                "6five3hqbjsrzhtkv7\r\n" + //
                "4pgcsxslr6h623\r\n" + //
                "three8one\r\n" + //
                "8xnsgbjhz9\r\n" + //
                "3gtqbhdzjninetwo6thrfssxqptjbtmkkmlddhdm\r\n" + //
                "6mldxcjnxv9\r\n" + //
                "mc8one88\r\n" + //
                "h4\r\n" + //
                "fivefour2s\r\n" + //
                "9q\r\n" + //
                "fiveseven8two8lkrtvdqchbvnmzmlhgqbcx\r\n" + //
                "cpcgpg9cnbsixsix\r\n" + //
                "vglgjf9qzcspsnsbrktbnpnppzmgldtwo\r\n" + //
                "three2kllpcvmmgcseven\r\n" + //
                "twofivekvcnfpkplnv2threefivehvxpthree\r\n" + //
                "36h6hzfhhbtqgqfgthreesix\r\n" + //
                "86kkqqseven9\r\n" + //
                "7jgncdninejvmqdmone5sqjp\r\n" + //
                "seventhree4eight9three\r\n" + //
                "38knvgxrftdtwo1\r\n" + //
                "ksgjdlpxhztnlfc6hxncbgbmgzldvlvmgrjkmtwosix\r\n" + //
                "dtoneightone427\r\n" + //
                "3518msltkgqthvjhs\r\n" + //
                "75qmqvkmf5six\r\n" + //
                "85pvvthreeseven\r\n" + //
                "ckqoneight4xqqnkdnzpggmxrmhkhx171nineqgd\r\n" + //
                "76nine\r\n" + //
                "6threentcfsvvfseven1eight\r\n" + //
                "23fivetlqdfhxgg312nine\r\n" + //
                "1pjninexlqnthreeoneoneoneightx\r\n" + //
                "6one1\r\n" + //
                "lfjmdhpj9fiveonelvfivenine\r\n" + //
                "4xjmxfxxfsbxgk9sixhq\r\n" + //
                "8six8vszdsslqntzjqxx8two\r\n" + //
                "4one88995five\r\n" + //
                "nskmvtzd1five\r\n" + //
                "4tpzxkbfq1vlxpvzbxnhqtshzhfourtwo\r\n" + //
                "7six341gsl77eight\r\n" + //
                "94dvc\r\n" + //
                "qzkmxqqh6sixvn\r\n" + //
                "sevenoneone26m8\r\n" + //
                "ninedtfvl3four15eightjtpfhlzzct9\r\n" + //
                "5ninesixtvvpblfqgb\r\n" + //
                "5twoseven4onedcsqj6\r\n" + //
                "gcbtzns6eight52ccvvpsbdgfgg\r\n" + //
                "tczvbfxfvcbfxzvvxp9three\r\n" + //
                "fourkczgcb9knnpkd3\r\n" + //
                "9ninefive8nine5\r\n" + //
                "tnkpsxjm7four45bpdg\r\n" + //
                "twofour1glkvvkq\r\n" + //
                "fiveeightfive8vbqtsmhjqr5vgbmsxrkh7four\r\n" + //
                "lhncnxngfour9five\r\n" + //
                "5six36five4\r\n" + //
                "74ckc\r\n" + //
                "lkeightwol11\r\n" + //
                "five3mnlbmsg2\r\n" + //
                "hmvmgnqlhdgonedxmjxxbpbpt1four6zh\r\n" + //
                "svmmzbbj5\r\n" + //
                "3l4\r\n" + //
                "1dgfnone17\r\n" + //
                "667\r\n" + //
                "1qlcg4seven\r\n" + //
                "756ghcxrmrgtninefivegvmtjhfrj\r\n" + //
                "6twonehjv\r\n" + //
                "vpgeight7twonlcfcdspmvpcfj6five2\r\n" + //
                "76jhj4sixeight\r\n" + //
                "vcfrscgccnine6j\r\n" + //
                "mhm8kfjl33ninefivethree\r\n" + //
                "85bfqjpdmbg92rjbthcrfgvcjzqhpgb\r\n" + //
                "nine554ltcgj5\r\n" + //
                "eightfivevjszdqkf96ninemgldmdth1nine\r\n" + //
                "sixq4pcczfqc\r\n" + //
                "three7two\r\n" + //
                "eight9csevenfour\r\n" + //
                "fpnnxvcttscfrgponefive8twohgfkhbssix\r\n" + //
                "smkjtzm72vmtleightjmkxkgpfzmjpmbbd\r\n" + //
                "7two1lxvqqzzrvj31fourprzmsdzbf\r\n" + //
                "kffeightwogzcqpzdbhfvmckxmbhrgvonevcshkbctbc524\r\n" + //
                "fcsoneightnmtgzbbnflnnlk5two\r\n" + //
                "6gkxbhgzbmltwosrmone1five\r\n" + //
                "sjrfkfjszsix49\r\n" + //
                "47seven82fourfhhfmlshdsix\r\n" + //
                "sixhjqszlc6kzzbqsldk\r\n" + //
                "nineptfourrvrghq7\r\n" + //
                "4four5one148jcbvnbj6\r\n" + //
                "ninezfcrvxfnjd6nine\r\n" + //
                "bfjfbpfseven7\r\n" + //
                "bdzmktwo4fourkrjj3\r\n" + //
                "nhnfv725\r\n" + //
                "sixeightsixkkndrj7\r\n" + //
                "eightone2m246\r\n" + //
                "fourhsbdblm74fourcphtwo\r\n" + //
                "khrjxxrltbpngsmzndgsjmzvgqxfhvkct6eightzrvpmpcc3\r\n" + //
                "mlsc4qnlhqjfour\r\n" + //
                "956onefive\r\n" + //
                "1xtmbmkscvv2onefivelvlztjtctz5eightnine\r\n" + //
                "32tmphhjnlfsixskninekjdcftm\r\n" + //
                "krgp1hdhgvgpgbvbxgfngvktwo\r\n" + //
                "klpnpcplfhlztjgv17six\r\n" + //
                "5dsxngmpdvjhnlbhxmp7xqqtgdoneightdvm\r\n" + //
                "threeeight3t\r\n" + //
                "5fourlpqzq2two1oneqlq\r\n" + //
                "eightfivesixnineeightfour1\r\n" + //
                "52ppqztdggqgtphdfz4fkrkfztzzqldpg\r\n" + //
                "seven7zbone\r\n" + //
                "xg79onef6eighteight\r\n" + //
                "three6nvhnqeightgkttsvtwofive9\r\n" + //
                "rjsevenonefllcrdnbmqcmxqsq38\r\n" + //
                "twoseven2dppxgmlhr61onenine4\r\n" + //
                "sevenb3btzhscqbrxxjkhtzpv\r\n" + //
                "859two\r\n" + //
                "threetllmjmhdjr18two\r\n" + //
                "94tmvfpzmgvzsm1fmbhkhzffkzllx\r\n" + //
                "nlkndffq2three\r\n" + //
                "6ninemfour8rbxvj6\r\n" + //
                "7clxtxrt1lqg5\r\n" + //
                "onefivegjnfzkvg9\r\n" + //
                "fplrvmqjdfxvjdfivesix6rpnkfour\r\n" + //
                "5fivetwoxdgchbjjrckntlgblsxlcznfd\r\n" + //
                "eight7fourfour\r\n" + //
                "3kmtjlfbgssixmspkfzrgxtctksix4onetwones\r\n" + //
                "8five15sixthreeljsfive\r\n" + //
                "9lnn\r\n" + //
                "nine7pzrxnnkthreesdjxphsrf4hc8\r\n" + //
                "three6115nqhllcmpmzcfour\r\n" + //
                "vpqjnvmltx8fivefive\r\n" + //
                "vrlqlj5fivesixninebqhgcpgmgkmflvn\r\n" + //
                "76eighteight7\r\n" + //
                "8qkmnsjxbfhcpsvn4\r\n" + //
                "oneninexqdseven4threefive\r\n" + //
                "rpcvmnng162fivesixseven\r\n" + //
                "31628eightthree\r\n" + //
                "83d6fsfqdghztwo7bmvrlh\r\n" + //
                "gknfcdqlrs25\r\n" + //
                "9gkkth2ps\r\n" + //
                "bxnvsjxqleight9ninenine\r\n" + //
                "rsmcrqlnhsmjhspseven96vsckknrggbjd4tgtgbkxgvt\r\n" + //
                "8seveneightcxrh\r\n" + //
                "tkmfour8fivevl9one\r\n" + //
                "8mgrxk\r\n" + //
                "fourbgckqkeight6f\r\n" + //
                "threetwo3eight652pp\r\n" + //
                "ninefivetwojbhglxfxzfctwo8\r\n" + //
                "jmjtcvpsxzdbkbqthree1qmgznpbzlthree4six1\r\n" + //
                "foursix5\r\n" + //
                "6nbdzdlmqpdlgpcclc\r\n" + //
                "24\r\n" + //
                "pseven3threeeightseven\r\n" + //
                "7nine7gjdksbtqrrdsr\r\n" + //
                "5ppflb48tkcffone8six\r\n" + //
                "five2two7hstbbqzrninegbtwo2\r\n" + //
                "eightfblzpmhs4\r\n" + //
                "fbbdeightzzsdffh8jbjzxkclj\r\n" + //
                "3nine6five1";

        int result = CalculateEtalonnage(input);
        System.out.println("Valeur d'étalonnage: " + result);

    }

    public static int CalculateEtalonnage(String input) {
        String[] lines = input.split("\\n");
        int somme = 0;
        for (String line : lines) {

            int FChar = 0;
            int LChar = 0;

            for (int i = 0; i < line.length() - 1; i++) {
                char c = line.charAt(i);
                if (Character.isDigit(c)) {
                    if (FChar == 0) {
                        FChar = c;
                    } else
                        LChar = c;

                }
            }

            String number = Integer.toString(FChar) + Integer.toString(LChar);
            int value = Integer.parseInt(number);
            somme += value;

        }

        return somme;

    }
}